- name : app setup
  import_role :
    name : common
    tasks_from : app-setup.yaml

- name : java setup
  import_role :
    name : common
    tasks_from : java.yaml
  
- name : systemd setup
  import_role :
    name : common
    tasks_from : systemd-setup.yaml

- name : install mysql
  package :
    name : mysql
    state : present
