[localhost]
local

[mongodb]
mongodb.dinakardevops.online

[redis]
redis.dinakardevops.online

[mysql]
mysql.dinakardevops.online

[user]
user.dinakardevops.online

[cart]
cart.dinakardevops.online

[rabbitmq]
rabbitmq.dinakardevops.online

[catalogue]
catalogue.dinakardevops.online

[shipping]
shipping.dinakardevops.online

[payment]
payment.dinakardevops.online

[frontend]
dinakardevops.online