- name :  app setup
  import_role :
    name : common
    tasks_from : app-setup.yaml

- name : python setup
  import_role : 
    name : common
    tasks_from : python.yaml

- name : systemd service
  import_role:
    name : common
    tasks_from : systemd-setup.yaml


- name : enable and restart payment
  import_role : 
    name : common
    tasks_from : restart.yaml