- name : app setup
  import_role :
    name : common
    tasks_from : app-setup.yaml

- name : nodejs setup
  import_role :
    name : common
    tasks_from : nodejs.yaml

- name : systemd setup
  import_role :
    name : common
    tasks_from : systemd-setup.yaml

- name : restart
  import_role :
    name : common
    tasks_from : restart.yaml